config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  resources :users do
    resources :reviews 
    resources :subcategories, :only => [:index, :show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :reviews
  has_many :subcategories
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :subcategory
  validates_presence_of :location, :description, :rating
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :categories, through: :reviews
  has_many :subcategories, through: :reviews

  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @user = current_user
    @reviews = @user.reviews.order(rating: :desc)
    # @user = User.find(params[:user_id])
    # @subcategory = Subcategory.find(params[:id])
    # @reviews = @subcategory.reviews
    # @subcategories = Subcategory.all
    # @reviews = Review.all.order(:category_id, :subcategory_id, :rating)
    # @reviews = @subcategories.reviews
  end

  def new
    @user = User.find(params[:user_id])
    @review = Review.new
  end

  def create
    @user = User.find(params[:user_id])
    @review = @user.reviews.new(review_params)
    @subcategory_id = @review.subcategory.id
    if @review.save
      redirect_to user_subcategory_path(@user.id, @subcategory_id)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:category_id, :subcategory_id, :location, :variety, :description, :rating)
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # before_filter :authenticate_user!
  def show
    @subcategory = Subcategory.find(params[:id])
    @user = current_user
    @reviews = @user.reviews.where(:subcategory_id => @subcategory).order(rating: :desc)

    if @reviews.empty?
      redirect_to user_path(@user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    if @user != current_user
    #   render 'show'
    # else
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowItRates</title>
  <link href='http://fonts.googleapis.com/css?family=Over+the+Rainbow' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">How It Rates</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
              <li><%= link_to "Sign In", new_user_session_path, method: :get %></li>
              
            <% end %>
            <% if current_user %>
              <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-success navbar-btn"%></li>
            <% end %>
          </ul>
        </div>  
      </div>
    </nav>
  

  <!-- <div class="container"> -->
    <!-- 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
      <%= yield %>
   
  <!-- </div> -->
</body>
</html>

app/views/reviews/index.html.erb
  <h2><%= current_user.first_name %>'s List</h2>

  <h3>Your List has <%= pluralize(current_user.reviews.count, "review") %>.</h3>


<div class="jumbotron">
  <% @reviews.each do |review| %>
    <p>
      <strong>Category:</strong>
      <%= review.subcategory.name %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= review.location %>
    </p>
     <p>
      <strong>Type:</strong>
      <%= review.variety %>
    </p>
     <p>
      <strong>Description:</strong>
      <%= review.description %>
    </p>
     <p>
      <div class="star-rating" data-score= <%= review.rating %> ></div>
    </p><br>
  <% end %>

  <%= button_to 'Add Review', new_user_review_path, method: :get, class: "btn btn-success" %>
</div>

<script>
  $(".star-rating").raty({
    path: "/assets/",
    readOnly: true,
    score: function() {
      return $(this).attr("data-score");
    }
  });
</script>

app/views/reviews/new.html.erb
<div class="container add-review">
  <%= form_for([@user, @review], html: {class: "form-horizontal"}) do |f| %>
      <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@review.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :category, class: "col-sm-2 control-label" %>
      <div id="category" class="col-sm-4">
        <%= f.collection_select :category_id, Category.order(:name), :id, :name, {prompt: "Select One"}, class: 'form-control' %>
      </div>  
    </div>
     <div class="form-group">
      <%= f.label :subcategory, class: "col-sm-2 control-label" %>
      <div id="subcat" class="col-sm-4">
        <%= f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, {prompt: "Select One"},  class: 'form-control' %>
      </div>  
    </div>
    <div class="form-group">
      <%= f.label :location, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :location, class: 'form-control' %>
      </div>  
    </div>
    <div class="form-group">
      <%= f.label :variety, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :variety, class: 'form-control' %>
      </div>  
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_area :description, class: 'form-control' %>
      </div>  
    </div>
    <div class="form-group">
      <%= f.label :rating, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <div id="star-rating"></div>
      </div>  
    </div>
    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
  </script>

app/views/subcategories/show.html.erb
<!-- <div class="jumbotron"> -->
  
  <h3><%= @subcategory.name %></h3>    

  <table class="table table-bordered">
  <thead>
    <tr>
      <th>Type</th>
      <th>Location</th>
      <th>Description</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.variety %></td>
        <td><%= review.location %></td>
        <td><%= review.description %></td>
        <td class="star-rating" data-score= <%= review.rating %> ></td>
      </tr>
    <div></div>
    <% end %>
  </tbody>
</table> 
    

    
  

  <%= button_to 'Add Review', new_user_review_path, method: :get, class: "btn btn-success" %>
  <%= button_to 'Back to My Page', user_path(current_user), method: :get, class: "btn btn-success" %>
<!-- </div> -->

<script>
  $(".star-rating").raty({
    path: "/assets/",
    readOnly: true,
    score: function() {
      return $(this).attr("data-score");
    }
  });
</script>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron hello-user" > 
    
    
      <h2>Hello <%= current_user.first_name %>. </h2>
    
  </div> 



  <div class="container-marketing">
    
      <div class="row">
       
        <% @user.categories.uniq.each do |category| %>
          <div class="col-lg-4">
            <a href="#" class="cats-panel"><h3><%= category.name %></h3></a>
            <div class="subcats-panel">
              <% if @user.subcategories.any? %>
                <% category.subcategories.each do |subcategory| %>
                  <% if subcategory.reviews.any? %>
                    <h4><%= link_to "#{subcategory.name}", user_subcategory_path(@user.id, subcategory.id) %></h4>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h2>Keep track of what you like and what you don't.</h2><br>
        <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "btn btn-lg btn-info navbar-btn" %>
    </div>
</div>